# Generated by Django 4.1.13 on 2026-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nivel_id_alter_partida_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('jugador', 'Jugador')], default='jugador', max_length=10),
        ),
    ]
