# Generated by Django 6.0.2 on 2026-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auth_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lockout_count',
            field=models.IntegerField(default=0),
        ),
    ]
