# Generated by Django 5.1.15 on 2026-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_confirmacionreset'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['usuario', '-fecha'], name='idx_partida_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['nivel', '-fecha'], name='idx_partida_nivel_fecha'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['-puntuacion'], name='idx_partida_puntuacion'),
        ),
    ]
