# Generated by Django 6.0.2 on 2026-09-21 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_confirmado_to_confirmacionreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionreset',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VerificacionEmail',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verificaciones_email',
            },
        ),
    ]
