# Generated by Django 6.1.1 on 2026-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuario_desactivado_por_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
