version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: free_ricky_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: free_ricky
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: free_ricky_backend
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_NAME: free_ricky
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      SECRET_KEY: tu_clave_secreta
      DEBUG: "True"

  frontend:
    build: ./frontend
    container_name: free_ricky_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: